### ISSUE TITLE
Launch other application

### ISSUE THREAD

**Issue by calebeaires** [NathanaelA/nativescript-openurl#1]
It would be very useful if your plugin could open another app too.

**Comment by NathanaelA** [comment]
Actually I believe it can if you know the name of the app; or the url actually points to a document that is exclusively opened by the app...

**Comment by utkarsh-srivastava** [comment]
Hi Nathanael, I was working with the module and wanted to know If i want to open instagram application from my application then what string should I pass as a location.
openurl('what should be here???')
Thanks

**Comment by OPADA-Eng** [comment]
@NathanaelA Can you please tell @utkarsh-srivastava  what is the string ?

**Comment by NathanaelA** [comment]
@OPADA-Eng - Sorry, I have no idea; never needed to open up instagram; so I haven't done any research into the proper url for instagram.   I would recommend you google it...
