### ISSUE TITLE
I have Error in IOS 10.3

### ISSUE THREAD

**Issue by vladyhon** [NathanaelA/nativescript-openurl#2]
Please change this:
`        if (UIApplication.sharedApplication().canOpenURL(url)) {
            return UIApplication.sharedApplication().openURL(url);
        }
`
to:
`
        if (UIApplication.sharedApplication.canOpenURL(url)) {
            return UIApplication.sharedApplication.openURL(url);
        }
`

because sharedApplication function doesn't exist

**Comment by NathanaelA** [comment]
This plugin has been depreciated -- it is now shipped as part of the NativeScript core library;   It is in the `utils` namespace.
